spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
env: 
  test1